### ISSUE TITLE
Proposal: Add equivalent to cl-unicode:has-property

### ISSUE THREAD

**Issue by Symbolics** [sabracrolleton/uax-15#11]
I am trying to bring my Genera version of Postmodern up to the latest. A lot has changed in the last few years. One of the stumbling blocks is `cl-unicode`. This triggers a bug in Genera that is beyond my ability to fix, and unless one of Symbolics paying customers runs into it, I doubt it will ever be addressed.

The only function from this library used in Postmodern is `has-property`, in [utils.lisp](https://github.com/marijnh/Postmodern/blob/c41c96b22a35162e1f4848392133d916084e58dc/postmodern/util.lisp), where it is used in two places to determine if a letter is a character.

Could this functionality be added here so that the dependency on `cl-unicode` could be removed from Postmodern?

**Comment by sabracrolleton** [comment]
Will replicating that functionality here or in Postmodern trigger the same Genera bug?

**Comment by Symbolics** [comment]
I don't think so. The bug in Genera is due to a very long alist in the generated code of cl-unicode and the way CLOS is implemented.

**Comment by sabracrolleton** [comment]
Willing to look at any proposed code. Since I do not have Genera, I cannot test what will trigger a bug and what will not.

**Comment by Symbolics** [comment]
I wouldn't have a clue on how to do this, but I can give it a try. I've never worked with unicode. Have you got anything existing in UAX that might be used as a start?

**Comment by sabracrolleton** [comment]
Ok. Let me give it a shot as a separate package, do the minimum and you see if it compiles on Genera. Let's take this offline. You have my email.

**Comment by sabracrolleton** [comment]
I think this is done, so will close and let you reopen if necessary
