### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [sabracrolleton/uax-15#6]
Building with SBCL 2.1.0.29-a1ce59262 / ASDF 3.3.1 for quicklisp dist creation.

Trying to build commit id a6ca59f8e68060fe16f9061459264a90f7849410

*uax-15* fails to build with the following error:

```
Unhandled SB-INT:SIMPLE-PROGRAM-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001A40103}>: invalid number of arguments: 4

```

*uax-15/tests* fails to build with the following error:

```
Unhandled SB-INT:SIMPLE-PROGRAM-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001A40103}>: invalid number of arguments: 4

```

[Full log here](http://report.quicklisp.org/2021-01-06/failure-report/uax-15.html)

**Comment by sabracrolleton** [comment]
Corrected typo
