### ISSUE TITLE
Tests fail under SBCL: No test or package found for UAX-15-SYSTEM::SUITE

### ISSUE THREAD

**Issue by Symbolics** [sabracrolleton/uax-15#8]
This is because, at the time the [test system is defined](https://github.com/sabracrolleton/uax-15/blob/705320c713f0bac5d82a5efdb3b432090a87fe9e/uax-15.asd#L25), we are [in package](https://github.com/sabracrolleton/uax-15/blob/705320c713f0bac5d82a5efdb3b432090a87fe9e/uax-15.asd#L5) `uax-15-system`.

I would suggest removing the following lines from the system definition file:
```lisp
(defpackage :uax-15-system
  (:use :common-lisp :asdf))
(in-package :uax-15-system)
```
The [ASDF best practices guide](https://github.com/fare/asdf/blob/master/doc/best_practices.md#trivial_packaging) suggests this is a bad practice.

Alternatively, the `test-op` can be redefined with fully qualified symbols:
```lisp
(uiop:symbol-call :parachute '#:test 'uax-15-tests::suite :report 'parachute:quiet)
```
Edit: I found a third alternative: use the `uiop:find-symbol*` function, which was apparently designed for this purpose.

**Comment by Symbolics** [comment]
@sabracrolleton, I've submitted a PR that takes care of this, whilst leaving in place the `uax-15-system` package. I still suggest removing it though. I've been doing a lot of ASDF/UIOP work recently and know that it's not needed.

If you're happy for me to make the change in removing it, I'm happy to do so and do a bit of ASDF cleaning.

**Comment by sabracrolleton** [comment]
Yes, please add the removal to the PR and add the asdf cleaning.

Thanks.

**Comment by Symbolics** [comment]
Done.

Also fixed a warning from SBCL about an undefined variable:
```lisp
; file: s:/src/third-party/uax-15/src/precomputed-tables.lisp
; in: LET ((UAX-15::CANONICAL-COMP-MAP (MAKE-HASH-TABLE :TEST #'EQUAL)))
;     (MAPHASH
;      (LAMBDA (UAX-15::SRC-CHAR UAX-15::DECOMPED-CHARS)
;        (WHEN (AND (= 2 #) (NOT #)) (SETF # UAX-15::SRC-CHAR)))
;      UAX-15::*CANONICAL-DECOMP-MAP*)
; --> LET* 
; ==>
;   (SB-IMPL::HASH-TABLE-PAIRS UAX-15::*CANONICAL-DECOMP-MAP*)
; 
; caught WARNING:
;   undefined variable: UAX-15::*CANONICAL-DECOMP-MAP*
```
The global variable was being defined at other than the top-level.

**Comment by sabracrolleton** [comment]
Thanks.
